spring:
  data:
    mongodb:
      username: developer
      password: KgUWqmhuO
      database: acintyo-mysaa
      port: 27019
      host: 45.127.101.159
      authentication-database: acintyo-mysaa
      auto-index-creation: true
			

  servlet:
   multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    
  boot:
   admin: 
    client:
      url: http://localhost:8125
      enabled: true
      auto-registration: true
     
               
  cloud:    
   gcp:
     credentials:
       location : classpath:service-account.json
       
  application:
      name: API-AUTH
      
  config:
    activate:
      on-profile: dev
      

cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAVS3HG73RBF7V475V
      secretKey: 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

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      


    import: classpath:aws.properties

      
springdoc:
  swagger-ui:
    path: api-auth/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
    register-with-eureka: false
    healthcheck:
      enabled: true 
    fetch-registry: true 
  instance:
   prefer-ip-address: true
   
server:
  Port: 8081
  
smsUrl: https://api.msg91.com/api/v5/otp
  
templateId: 64ead72dd6fc0523e927f6f2
  
authkey: 374579AeR6hq3x6231b4a2P1
  
otplength: 4
  
otpexpiry: 3
  
countyCode: 91

bucketName: acintyotech-public

userDefalutImgId: https://acintyotech-public.s3.ap-south-1.amazonaws.com/assets/70f4d4da-dbf3-435c-b7c6-d7cf27aa3866.png


logging:
 file: 
  name: auth.log
  max-hitory: 20
  max-size: 20MB
 
management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 
  endpoint:
    health:
      show-details: always      
      
otplengthMysaa: 4


google:
  token-validation:
    cache-timeout-minutes: 30

distanceInKilometers: 5

my:
  feign:
    client:
      wallet: API-WALLET
      auth: API-AUTH
      banner: API-BANNER
      fcm: API-FCM
			
			

			
